demokratikollen/www/app/views/pages.py
# -*- coding: utf-8 -*-

from datetime import datetime

# Import flask dependencies
from flask import request, render_template, \
                  flash, g, session, redirect, url_for

# Import the database object from the main app module
from demokratikollen.www.app.helpers.cache import cache, http_expires
from demokratikollen.www.app.helpers.db import db
from demokratikollen.core.db_structure import Member, ChamberAppointment, Party
from demokratikollen.www.app.models.proposals import proposals_main
from demokratikollen.www.app.models.parliament import latest_chamber_appointment
from demokratikollen.www.app.models.sitemap import sitemap_pages
from flask import Blueprint, request, jsonify, Markup
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy import func
from demokratikollen.core.utils.mongodb import MongoDBDatastore


blueprint = Blueprint('pages', __name__)

def render_parliament():
    return render_template("/parliament/index.html", latest_chamber_apointment_date=latest_chamber_appointment())

# Set the route and accepted methods
@blueprint.route('/', methods=['GET'])
def index():
    return render_parliament()

@blueprint.route('/riksdagen', methods=['GET'])
def parliament():
    return render_parliament()

@blueprint.route('/partierna', methods=['GET'])
def parties():
    return render_template("/parties/index.html")

@blueprint.route('/forslagen/<string:gov>', methods=['GET'])
def proposals(gov):

    try:
        proposals_main_data = proposals_main(gov)
    except KeyError:
        return render_template('404.html'), 404

    return render_template("/proposals/index.html",
                                data = proposals_main_data
                               )

@blueprint.route('/om', methods=['GET'])
def about():
    return render_template("/about.html")

@blueprint.route("/sitemap.xml")
def sitemap():
    pages = sitemap_pages()
    return render_template("/sitemap.xml", pages=pages)

@blueprint.route("/sekretesspolicy.html")
def privacypolicy():
    return render_template("/privacypolicy.html")

@blueprint.route('/search.json', methods=['GET'])
@http_expires(3600*24)
@cache.cached(3600*24)
def timeseries():
    ds = MongoDBDatastore()
    return jsonify(ds.get_object("search"))

def render_party(p):
    return render_template("/parties/party.html",party=p)
def render_member(m):
    return render_template("/parliament/member.html", member=m)

@blueprint.route('/<arg>', methods=['GET'])
def missing(arg):
    # first try party abbreviations
    try:
        p = db.session.query(Party).filter(func.lower(Party.abbr)==arg.lower()).one()
        return render_party(p)
    except NoResultFound as e:
        pass        

    # try party full name
    try:
        p = db.session.query(Party).filter(func.lower(Party.name)==arg.lower()).one()
        return render_party(p)
    except NoResultFound as e:
        pass

    # try member url_name
    try:
        m = db.session.query(Member).filter(Member.url_name==arg.lower()).one()
        return render_member(m)
    except NoResultFound as e:
        pass

    return render_template('404.html'), 404

demokratikollen/www/app/templates/about.html
{% extends "base.html" %}
{% set title = "Om - Demokratikollen" %}

{% block content %}
<h2>Om Demokratikollen</h2>
<div class="row">
	<div class="text-col">
		<p>Demokratikollen är politiskt oberoende och utvecklas och drivs ideellt. All information som visas på sidan är baserad på <a href="http://data.riksdagen.se">riksdagens öppna data</a>, samt valresultat och resultat från väljarundersökningar ur SCBs <a href="http://www.scb.se/sv_/Hitta-statistik/Statistik-efter-amne/Demokrati/">demokratistatistik</a>.</p>

		<p>Skicka gärna förslag och synpunkter till <a href="mailto:synpunkter@demokratikollen.se">synpunkter@demokratikollen.se</a>!</p>
	</div>
</div>



{% endblock %}

demokratikollen/www/app/templates/base.html
{% extends "layout.html" %}

{% set title = title|default("Demokratikollen") %}

{% set open_graph_type = open_graph_type|default("article") %}
{% set open_graph_image = open_graph_image|default("demokratikollen.png") %}
{% set open_graph_description = open_graph_description|default("Interaktiva visualiseringar om politiken i Sverige: Riksdagen, partierna, valresultat, ledamöterna. Demokratikollen är baserad på öppna data från Riksdagen och SCB.") %}

{% set nav_buttons = [
    ('/riksdagen', 'Riksdagen'),
    ('/partierna', 'Partierna'),
    ('/forslagen/reinfeldt2', 'Förslagen')
] -%}

{% set active_button = active_button|default(None) -%}
{% block menu_links %}
  {% for href, caption in nav_buttons -%}
    <li{% if caption == active_button %} class="active"{% endif
    %}><a href="{{ href|e }}">{{ caption|e }}
    {%- if caption == active_button -%}
    <span class="sr-only"> (du är här)</span>
    {%- endif -%}
    </a>
    </li>
  {%- endfor %}
{% endblock %}

{% block content %}
<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

demokratikollen/www/app/templates/index.html
{% extends "base.html" %}

{% set open_graph_type = open_graph_type|default("website") %}

{% block content %}
<div class="row text-div">
    <div class="col-xs-12">
        <h2>Välkommen!</h2>
        <p>
            Välkommen till Demokratikollen, ett steg närmre politikens dolda korridorer. Vilket parti röstar med vilket? Vilken ledamot har flest uppdrag? (mera!). Dessa och många fler frågor kan du få svar på genom att utforska denna sida. 
        </p>
    </div>
</div>
<div id="teaser-slider" class="row">
    <div class="image-slider col">
        <ul>
            <li>
                <a href="{{ url_for('pages.parliament') }}" alt="Länk till sidan för en översikt över parlamentet">
                    <img src="img/slider_parliament.jpg">
                </a>
            </li>
            <li><a href="/m"><img src="img/slider_party.jpg"></a></li>
            <li><a href="/partierna"><img src="img/slider_parties.jpg"></a></li>
        </ul>
    </div>
</div>


{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
      $(function() { $('div.image-slider').unslider({fluid: true, dots: true}); });
    </script>
{%- endblock %}

demokratikollen/www/app/templates/layout.html
<!DOCTYPE html>
<html lang="sv">
  <head>
    {% block head -%}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    <link href="{{ url_for('static', filename='css/dependencies.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/styles.min.css') }}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,700,400,600|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>

    <meta property="og:site_name" content="Demokratikollen" />
    <meta property="og:title" content="{{ title | replace(" - Demokratikollen", "") }}" />
    <meta property="og:type" content="{{ open_graph_type }}" />
    <meta property="og:description" content="{{ open_graph_description }}" />
    <meta property="og:url" content="http://www.demokratikollen.se{{ request.path | lower }}" />
    <meta property="og:image" content="http://www.demokratikollen.se/img/opengraph/{{ open_graph_image }}" />
    <meta property="og:locale" content="sv_SE" />

    <meta property="fb:admins" content="100009144606221" />
    <meta property="fb:admins" content="526571212" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@demokratikollen" />
    <meta name="twitter:creator" content="@demokratikollen" />
    <meta name="twitter:title" content="{{ title }}" />
    <meta name="twitter:description" content="{{ open_graph_description }}" />
    <meta name="twitter:image:src" content="http://www.demokratikollen.se/img/opengraph/{{ open_graph_image }}" />

    <meta name="description" content="{{ open_graph_description }}"/>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {%- endblock %}
    {% block styles %}{% endblock %}
  </head>
  <body>
  <div id="fb-root"></div>
  <script>
  window.fbAsyncInit = function() {FB.init({appId: '1541141682820916', xfbml: true, version: 'v2.2'});};
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/sv_SE/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

    <nav id="navbar" role="navigation">
      <div>
        <div class="container">
          <div class="row">
            <div class="column brand-and-menu-toggle">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div>
                <a class="brand" href="/">Demokratikollen<span class="period">.</span></a>
                <button id="menu-toggle" type="button collapsed" data-toggle="collapse" data-target=".collapse">
                  <span class="sr-only">Visa/dölj navigering</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
            </div><!-- end columns -->


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="column menu-search">
              <div class="collapse">
                <form role="search">
                  <div class="search">
                    <div class="search-typeahead" id="main-search">
                      <span class="input-group-addon"><span aria-hidden="true"></span></span>
                      <input type="text" placeholder="Sök ledamot eller parti" id="searchbox" autocomplete="off">
                      <ul id="searchresults">
                      </ul>
                    </div>
                  </div><!-- /input-group -->
                </form>
              </div>
            </div><!-- end columns -->
            <div class="column menu-links">
              <div class="collapse">
                <ul class="menu-links">
                {% block menu_links %}
                <li class="active"><a href="#">Exempel 1<span class="sr-only"> (du är här)</span></a></li>
                <li><a href="#">Exempel 2</a></li>
                <li><a href="#">Exempel 3</a></li>
                {% endblock %}
                </ul>
              </div>
            </div><!-- end columns -->
          </div><!-- /.row -->
        </div><!-- /.container -->
      </div><!-- /.navbar-inner -->
    </nav>

    
    <div id="content-wrapper">
      <div class="container">
      <div id="fb-twitter">
        <div class="inner">
          <a href="https://twitter.com/share" class="twitter-share-button" data-via="demokratikollen" data-lang="sv">Tweeta</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
          <div class="fb-like" data-href="http://www.demokratikollen.se{{ request.path | lower }}" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
        </div>
      </div>
        {% block content %}{% endblock %}
      </div>
    </div>

    <footer>
      <div class="container">
        <p class="left">&copy; 2014 Demokratikollen</p><p class="right"><a href="/om">Om Demokratikollen</a></p>
      </div>
    </footer>

    <cookienotice>
      <div>
        <p class="center">
          Demokratikollen använder kakor för att kunna ge dig en bättre upplevelse. <a href="{{url_for('pages.privacypolicy')}}">Läs mer i vår sekretesspolicy.</a>
        </p>
        <input id="cookie-consent-button" type="button" value="Jag förstår och accepterar">

      </div>
    </cookienotice>

    {%- block scripts %}
    <script src="{{ url_for('static', filename='js/dependencies.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scripts.min.js') }}"></script>
    <script type="text/javascript">$(demokratikollen.initSearch());</script>
    {%- endblock %}
  </body>
</html>

demokratikollen/www/app/templates/privacypolicy.html
{% extends "base.html" %}
{% set title = "Sekretesspolicy - Demokratikollen" %}

{% block content %}
<div class="row">
  <div class="text-col">
<h1>Sekretesspolicy</h1> 
<p>Demokratikollen använder
cookies för att kunna göra sidan bättre i framtiden. Vi använder oss av två
tredjepartsmjukvaror: Google Analytics och New Relic.</p>

<h3>Google Analytics</h3> 
Google Analytics samlar in data för att
besökstatistik och annonsunderlag för Demokratikollen. För en utförlig
beskrivning av Googles användning av datan samt hur du kan ställa in vilken
information Google samlar in från dig, <a
href="http://www.google.com/policies/privacy/partners/">se deras
partnervillkor</a>.

<h3>New Relic</h3> 
New Relic är en tjänst som framförallt mäter prestandan för
Demokratikollen. Datan är helt anonymiserad och varken New Relic eller
Demokratikollen kan identifiera dig som person. För mer information, <a
href="http://newrelic.com/privacy">se deras egna sekretesspolicy</a>, främst
avsnittet <em>Use of Your Application Data</em>

<h3>Jag vill inte bli förföljd</h3>  
<p>   
Tyvärr kan inte New Relics tjänst
stängas av per användare. Om du inte vill att data skall samlas in från dig
rekommenderar vi att du blockerar cookies från demokratikollen.se . För
instruktioner hur du gör detta, se guiden för din webläsare: </p>
<ul>
<li><a href="https://support.google.com/chrome/answer/95647?hl=sv">Chrome</a> </li>
<li><a href="https://support.mozilla.org/sv/kb/Till%C3%A5t%20eller%20blockera%20kakor">Firefox</a> </li>
<li><a href="http://windows.microsoft.com/sv-se/internet-explorer/delete-manage-cookies">Internet Explorer<a> </li>
<li><a href="http://support.apple.com/kb/PH17191">Safari Mac</a> </li>
<li><a href="http://support.apple.com/sv-se/HT1677">Safari iOS</a> </li>
<li><a href="https://support.google.com/chrome/answer/2392971?hl=sv">Android Chrome</a> </li>


</div>
</div>



{% endblock %}